name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Use a stable version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirement.txt ]; then pip install -r requirement.txt; fi

    - name: Run linter
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/movecloud-flask-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/movecloud-flask-app:latest

    - name: Deploy to server (Optional)
      if: github.ref == 'refs/heads/main'
      run: |
        ssh user@your-server 'docker pull ${{ secrets.DOCKER_USERNAME }}/movecloud-flask-app:latest && docker run -d --rm -p 80:5000 --name movecloud-flask-app-container ${{ secrets.DOCKER_USERNAME }}/movecloud-flask-app:latest'
